# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'location' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for location
  #pod 'QuadratTouch', '>=1.0'
  #pod 'QuadratTouch', :git =>'https://github.com/Constantine-Fry/das-quadrat.git'
  #pod 'RealmSwift'
  pod "youtube-ios-player-helper", "~> 0.1.4"
end
